// data.ts

import { Avaliador, Trabalho } from "./types";

export const MAX_NOTA = 10;

export const AVALIADORES: Avaliador[] = [];

export const TRABALHOS: Trabalho[] = [
  {
    id: "1",
    titulo: "Circuito líquido, acende ou não",
    equipe: "G1",
    avaliadores: ["10", "30"],
    hasObservacoes: true,
  },
  {
    id: "2",
    titulo: "Vesúvio Elétrico",
    equipe: "G2",
    avaliadores: ["19", "20"],
    hasObservacoes: false,
  },
  {
    id: "3",
    titulo: "O avanço mais importante da Eletricidade",
    equipe: "G3",
    avaliadores: ["19", "32"],
    hasObservacoes: false,
  },
  {
    id: "4",
    titulo: "Maresia",
    equipe: "G4",
    avaliadores: ["8", "4"],
    hasObservacoes: false,
  },
  {
    id: "5",
    titulo: "A biodiversidade amazônica e sua importância para o planeta",
    equipe: "G5",
    avaliadores: ["6", "13"],
    hasObservacoes: false,
  },
  {
    id: "6",
    titulo: "Indicador de pH com repolho roxo",
    equipe: "G6",
    avaliadores: ["30", "12"],
    hasObservacoes: false,
  },
  {
    id: "7",
    titulo: "Tubo de Rubens",
    equipe: "G7",
    avaliadores: ["21", "32"],
    hasObservacoes: false,
  },
  {
    id: "8",
    titulo: "Linhas de campo magnético com Limalha de ferro",
    equipe: "G8",
    avaliadores: ["21", "33"],
    hasObservacoes: false,
  },
  {
    id: "9",
    titulo: "Perícia criminal .",
    equipe: "G9",
    avaliadores: ["8", "3"],
    hasObservacoes: false,
  },
  {
    id: "10",
    titulo: "Mão mecânica com sistema hidráulico",
    equipe: "G10",
    avaliadores: ["18", "17"],
    hasObservacoes: false,
  },
  {
    id: "11",
    titulo: "Cadeira de rodas com freio magnético e carregador de celular",
    equipe: "G11",
    avaliadores: ["27", "24"],
    hasObservacoes: false,
  },
  {
    id: "12",
    titulo: "Casos criminais e hematologia forense",
    equipe: "G12",
    avaliadores: ["31", "9"],
    hasObservacoes: false,
  },
  {
    id: "13",
    titulo: "Bobinas de Tesla",
    equipe: "G13",
    avaliadores: ["2", "19"],
    hasObservacoes: false,
  },
  {
    id: "14",
    titulo: "Museu Interplanetário",
    equipe: "G14",
    avaliadores: ["4", "27"],
    hasObservacoes: false,
  },
  {
    id: "15",
    titulo: "Aquecedor por indução",
    equipe: "G16",
    avaliadores: ["2", "17"],
    hasObservacoes: false,
  },
  {
    id: "16",
    titulo: "Passa ou Repassa",
    equipe: "G17",
    avaliadores: ["23", "7"],
    hasObservacoes: false,
  },
  {
    id: "17",
    titulo: "Segurança digital",
    equipe: "G18",
    avaliadores: ["20", "9"],
    hasObservacoes: false,
  },
  {
    id: "18",
    titulo: "A Biblioteca De Alexandria e seu legado cultural e artístico",
    equipe: "G19",
    avaliadores: ["15", "22"],
    hasObservacoes: false,
  },
  {
    id: "19",
    titulo: "AutoLar",
    equipe: "G20",
    avaliadores: ["5", "19"],
    hasObservacoes: false,
  },
  {
    id: "20",
    titulo: "Motor à Vapor",
    equipe: "G21",
    avaliadores: ["7", "24"],
    hasObservacoes: false,
  },
  {
    id: "21",
    titulo: "PH do Repolho Roxo",
    equipe: "G22",
    avaliadores: ["30", "12"],
    hasObservacoes: false,
  },
  {
    id: "22",
    titulo: "Biodiversidade marinha: A vida escondida nos oceanos",
    equipe: "G23",
    avaliadores: ["13", "26"],
    hasObservacoes: false,
  },
  {
    id: "23",
    titulo: "Protótipo de um guindaste",
    equipe: "G24",
    avaliadores: ["5", "18"],
    hasObservacoes: false,
  },
  {
    id: "24",
    titulo: "Xadrez para cegos profissional",
    equipe: "G25",
    avaliadores: ["28", "5"],
    hasObservacoes: false,
  },
  {
    id: "25",
    titulo: "Caixa de Areia Interativa: Ensinando Relevo com Tecnologia.",
    equipe: "G26",
    avaliadores: ["4", "8"],
    hasObservacoes: false,
  },
  {
    id: "26",
    titulo: "Dança da Areia",
    equipe: "G27",
    avaliadores: ["29", "28"],
    hasObservacoes: false,
  },
  {
    id: "27",
    titulo: "Trem e curva",
    equipe: "G28",
    avaliadores: ["11", "1"],
    hasObservacoes: false,
  },
  {
    id: "28",
    titulo: "Vida Marinha",
    equipe: "G29",
    avaliadores: ["16", "26"],
    hasObservacoes: false,
  },
  {
    id: "29",
    titulo: "Lumen Facimus",
    equipe: "G30",
    avaliadores: ["4", "6"],
    hasObservacoes: false,
  },
  {
    id: "30",
    titulo: "QuimioFísica: explorando a vida através da ciência",
    equipe: "G31",
    avaliadores: ["8", "25"],
    hasObservacoes: true,
  },
  {
    id: "31",
    titulo: "Garra Hidráulica",
    equipe: "G32",
    avaliadores: ["33", "27"],
    hasObservacoes: false,
  },
  {
    id: "32",
    titulo: "Pelos Trilhos de Santos Dumont",
    equipe: "G33",
    avaliadores: ["9", "20"],
    hasObservacoes: false,
  },
  {
    id: "33",
    titulo:
      "Representação prática dos trabalhos de Newton, as três leis e a decomposição da luz",
    equipe: "G34",
    avaliadores: ["31", "22"],
    hasObservacoes: false,
  },
  {
    id: "34",
    titulo: "ROBÔ GUINDASTE",
    equipe: "G35",
    avaliadores: ["1", "12"],
    hasObservacoes: false,
  },
  {
    id: "35",
    titulo: "Maquete com gerador eólico",
    equipe: "G36",
    avaliadores: ["23", "11"],
    hasObservacoes: false,
  },
  {
    id: "36",
    titulo: "Amassador de latinhas pneumático",
    equipe: "G37",
    avaliadores: ["25", "3"],
    hasObservacoes: true,
  },
  {
    id: "37",
    titulo: "InclusArte",
    equipe: "G38",
    avaliadores: ["20", "14"],
    hasObservacoes: false,
  },
  {
    id: "38",
    titulo: "Ecologia, preservação e importância da fauna marinha",
    equipe: "G39",
    avaliadores: ["16", "13"],
    hasObservacoes: false,
  },
  {
    id: "39",
    titulo: "Motor Elétrico -Reciclado-",
    equipe: "G40",
    avaliadores: ["2", "24"],
    hasObservacoes: true,
  },
  {
    id: "40",
    titulo:
      "Aerogerador Eólico :Geração Eólica Sustentável Aplicada ao Consumo Energético Natalino",
    equipe: "G41",
    avaliadores: ["23", "17"],
    hasObservacoes: false,
  },
  {
    id: "41",
    titulo: "O Eletroímã",
    equipe: "G42",
    avaliadores: ["1", "18"],
    hasObservacoes: false,
  },
  {
    id: "42",
    titulo: "Ciclone de Fogo",
    equipe: "G43",
    avaliadores: ["16", "29"],
    hasObservacoes: false,
  },
  {
    id: "43",
    titulo: "Motor Estrela",
    equipe: "G44",
    avaliadores: ["2", "32"],
    hasObservacoes: false,
  },
  {
    id: "44",
    titulo: "Usina de Chernobyl: Ciência e Catástrofe",
    equipe: "G45",
    avaliadores: ["15", "30"],
    hasObservacoes: true,
  },
  {
    id: "45",
    titulo: "Assédio e Discriminação: O que não se vê",
    equipe: "G46",
    avaliadores: ["14", "3"],
    hasObservacoes: false,
  },
  {
    id: "46",
    titulo: "Motor elétrico com imã",
    equipe: "G47",
    avaliadores: ["25", "10"],
    hasObservacoes: false,
  },
  {
    id: "47",
    titulo: "Desenvolvimento de um jogo online de perguntas e respostas",
    equipe: "G48",
    avaliadores: ["17", "11"],
    hasObservacoes: false,
  },
  {
    id: "48",
    titulo: "Melhoria Arma de plasma",
    equipe: "G49",
    avaliadores: ["10", "12"],
    hasObservacoes: false,
  },
  {
    id: "49",
    titulo: "Terrário - um ecossistema em miniatura",
    equipe: "G50",
    avaliadores: ["14", "8"],
    hasObservacoes: false,
  },
  {
    id: "50",
    titulo: "Microscópio de Água",
    equipe: "G51",
    avaliadores: ["25", "30"],
    hasObservacoes: true,
  },
].sort((a, b) => a.titulo.localeCompare(b.titulo));

export const EQUIPES = TRABALHOS.map((t) => t.equipe);
